format="""
[╭](fg:current_line)\
$os\
$username\
$directory\
$git_branch\
$fill\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$cmd_duration\
$time\
$line_break\
$character\
"""

palette = 'dracula'
add_newline = true

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue	= '#6272A4'
cyan = '#8BE9FD'
green	= '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red	= '#FF5555'
yellow = '#F1FA8C'

[os]
format = '(fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[](fg:red bg:box)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = '󰣇 '
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = 'win'

[username]
format = '[ $user ](fg:foreground bg:box)[](fg:box)'
show_always = true


[directory]
format = '[─](fg:current_line)[](fg:pink)[   ](fg:primary bg:pink)[](fg:pink bg:box)[ $read_only$truncation_symbol$path ](fg:foreground bg:box)[](fg:box)'
home_symbol = "~/"
# truncation_symbol = ' '
truncation_length = 2
# read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $branch](fg:foreground bg:box)[](fg:box)'
symbol = '  '

[nodejs]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' 󰎙 '
disabled = true 

[c]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '  '
disabled = true 

[cpp]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = "  "
disabled = true 

[rust]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = "  "
disabled = true 

[golang]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = "  "
disabled = true 

[php]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = "  "
disabled = true 

[dotnet]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $tfm](fg:foreground bg:box)[](fg:box)'
symbol = '  '
disabled = true 

[python]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '  '
disabled = true 

[java]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '  '
disabled = true 

[kotlin]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = "  "
disabled = true 

[haskell]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = "  "
disabled = true 

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:orange)[  ](fg:primary bg:orange)[](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[time]
format = '[─](fg:current_line)[](fg:purple)[ 󰦖 ](fg:primary bg:purple)[](fg:purple bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
disabled = false

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[>](fg:bold green)'
error_symbol = '[×](fg:bold red)'
