# import theme
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
# shell
shell = "/usr/bin/zsh"

# Window configuration
[window]
opacity = 1
decorations = "None"

[window.padding]
x = 10
y = 10
  
[scrolling]
multiplier = 3  # default

[font]
size = 16

[font.normal]
family =  "CaskaydiaCoveNerdFontMono"

[terminal]
osc52 = "CopyPaste"

